baseURL = 'https://phy-zhangzl.github.io'
languageCode = 'en-us'
title = "Prometheus's fire"
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 0

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Daily Reading"
    url = "/dailyreading/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4

  [[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  lineNos = true
  lineNumbersInTable = true
  noClasses = false

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  mainSections = ["posts"]
  ShowToc = true
  TocOpen = true
  comments = true

  [params.homeInfoParams]
    Title = "Zeal"
    Content = "Focus: Vibe Engineering, AI Agent."
  
  [[params.socialIcons]]
    name = "email"
    url = "mailto:phyzeal@linux.do"
