baseURL = 'https://phy-zhangzl.github.io'
languageCode = 'en-us'
title = "Prometheus's fire"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  
  [params.profileMode]
    enabled = true
    title = "zeal"
    subtitle = "This is zeal's blog. contact with me by phyzeal@linux.do"
    # imageUrl = "" # User will add later
    imageWidth = 120
    imageHeight = 120
  
  [[params.socialIcons]]
    name = "email"
    url = "mailto:phyzeal@linux.do"
